// The device library has one source of truth: ../devices.js in the extension.
// This copies it into src/ so the published package is self-contained.
import { readFileSync, writeFileSync } from 'node:fs';
const src = new URL('../devices.js', import.meta.url);
const out = new URL('./src/devices.js', import.meta.url);
writeFileSync(out, '// Generated by sync-devices.mjs from the extension\'s devices.js. Do not edit here.\n' + readFileSync(src, 'utf8'));
console.log('synced devices.js');
